# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

description = "A Hugo theme for my personal website based on Ananke"
features = ["posts", "shortcodes", "related content", "comments"]
homepage = "https://github.com/hawc2/hawc2.github.io"
min_version = "0.64.0"
name = "ananke"
