baseURL: https://hawc2.github.io
languageCode: en-us
defaultContentLanguage: en
title: Alex Wermer-Colan
theme: ananke

contentDir: content
menu:
  main:
    - name: Writing
      url: /writing
      weight: 1
    - name: Translating
      url: /translating
      weight: 2
    - name: Dramaturgy
      url: /dramaturgy
      weight: 3
    - name: Projects
      url: /projects
      weight: 4
    - name: Coding
      url: /coding
      weight: 5
    - name: Pedagogy
      url: /pedagogy
      weight: 6

params:
  site_logo: /images/headshot.jpg
  favicon: /favicon/favicon.ico
  featured_image: /images/hero.jpg
  cover_dimming_class: bg-black-10
  background_color_class: bg-dark-gray
  body_classes: helvetica black
  custom_css:
    - custom.css

markup:
  goldmark:
    renderer:
      # Allow HTML in markdown
      unsafe: true
