baseURL = 'http://hawc2.github.io/'
languageCode = 'en-us'
title = 'Alex Wermer-Colan'
theme = "researcher"

  description = "Alex Wermer-Colan is a writer, editor, translator, and technologist."
  cover = "images/cover.png" 
  ##save the image you want to use as background picture in directory "./static/images"
  author = "Alex"
  authorlocation = "authorlocation"
  logo = "images/logo.png" 
  ##save the image you want to use as website logo in directory "./static/images"
  githubName = "hawc2"
  linkedinName = "your linkedin name"
  email = "alwermercolan@gmail.com"
  twitterName = "alexwermercolan"
  
  hideHUGOSupport = false

[[menu.main]]  # here are the buttons on the menu 
  name = "Home" # Button will display as "Home"
  weight = 100 # the weight decides the position of the button (higher or lower)
  identifier = "home"
  pre = "<br />" 
  url = "/"

[[menu.main]]
  name = "Contact"
  weight = 0
  identifier = "contact" 
  # this button will refer to a markdown file named "contact" in the content folder
  pre = "<br />"
  url = "/contact"

[[menu.main]]
  name = "Blog"
  identifier = "blog"
   # this page will refer to a markdown file named "blog" in the content folder
  pre = "<br />"
  url = "/post"
  weight = 40
  
[permalinks]
  post = "/:slug/"

[sitemap]
  ChangeFreq = ""
  Filename = "sitemap.xml"
  Priority = "-1"

